repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.7.1
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/sirosen/texthooks
    rev: 0.2.2
    hooks:
      - id: fix-smartquotes
        args: ["--show-changes"]
      - id: fix-ligatures
        args: ["--show-changes"]
      - id: forbid-bidi-controls
