name: Python CI Pipeline

on:
  workflow_call:
    inputs:
      PYTHON_VERSION:
        required: false
        type: string
        default: "3.9"
      POETRY_VERSION:
        required: false
        type: string
        default: "1.2.2"


concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: doesnt-matter
      AWS_SECRET_ACCESS_KEY: doesnt-matter
    services:
      opensearch:
        image: opensearchproject/opensearch:1.1.0
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
          DISABLE_INSTALL_DEMO_CONFIG: true
          DISABLE_SECURITY_PLUGIN: true
        options: >-
          --name=opensearch
          --health-cmd="curl http://localhost:9200/_cluster/health"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout project repo
        uses: actions/checkout@v4

      - name: Checkout Reusable Workflows repo
        uses: actions/checkout@v4
        with:
          repository: mirta-com/workflows
          path: workflows-repo

      - name: Install requirements
        uses: ./workflows-repo/.github/actions/python/install-poetry-requirements
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PYTHON_VERSION: ${{ inputs.PYTHON_VERSION }}
          POETRY_VERSION: ${{ inputs.POETRY_VERSION }}

      - name: Run Linters
        uses: ./workflows-repo/.github/actions/python/lint

      - name: Run Tests
        run: make test
